@startuml

entity "Competitions" {
    * competition_id : INT
    * season_id : INT
    country_name : VARCHAR(255)
    competition_name : VARCHAR(255)
    competition_gender : VARCHAR(50)
    competition_youth : BOOLEAN
    competition_international : BOOLEAN
    season_name : VARCHAR(255)
}

entity "Matches" {
    * match_id : INT
    match_date : DATE
    kick_off : TIME
    country : VARCHAR(25)
    competition : VARCHAR(50)
    * competition_id : INT
    * season_id : INT
    home_team : VARCHAR(50)
    home_team_gender : VARCHAR(25)
    home_team_manager_id : INT
    home_team_manager_name : VARCHAR(100)
    home_team_group : VARCHAR(25)
    home_team_country : VARCHAR(50)
    away_team : VARCHAR(50)
    away_team_gender : VARCHAR(25)
    away_team_manager_id : INT
    away_team_manager_name : VARCHAR(100)
    away_team_group : VARCHAR(25)
    away_team_country : VARCHAR(50)
    home_score : INT
    away_score : INT
    match_status : VARCHAR(25)
    match_week : INT
    competition_stage : VARCHAR(25)
    stadium : VARCHAR(50)
    stadium_country : VARCHAR(25)
    referee_name : VARCHAR(125)
    referee_country : VARCHAR(50)
}

entity "Lineups" {
    * match_id : INT 
    lineup_details : JSONB
}

entity "Pass" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    recipient_name : VARCHAR(125)
    pass_length : NUMERIC
    pass_angle : NUMERIC
    pass_height : VARCHAR(50)
    end_location_x : NUMERIC
    end_location_y : NUMERIC
    deflected : BOOLEAN
    is_backheel : BOOLEAN
    is_cross : BOOLEAN
    is_cutback : BOOLEAN
    is_switch : BOOLEAN
    shot_assist : BOOLEAN
    goal_assist : BOOLEAN
    pass_body_part : VARCHAR(50)
    pass_type : VARCHAR(25)
    outcome_name : VARCHAR(50)
    technique : VARCHAR(50)
}

entity "Shot" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    end_location_x : NUMERIC
    end_location_y : NUMERIC
    end_location_z : NUMERIC
    aerial_won : BOOLEAN
    follows_dribble : BOOLEAN
    first_time : BOOLEAN
    open_goal : BOOLEAN
    statsbomb_xg : NUMERIC
    deflected : BOOLEAN
    technique_name : VARCHAR(50)
    body_part_name : VARCHAR(50)
    type_name : VARCHAR(50)
    outcome_name : VARCHAR(50)
}

entity "Dribble" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    overrun : BOOLEAN
    nutmeg : BOOLEAN
    no_touch : BOOLEAN
    outcome : VARCHAR(50)
}

entity "Dribbled_Past" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    counterpress : BOOLEAN
}

entity "Bad_Behaviour" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    card_colour : VARCHAR(25)
}

entity "Ball_Receipt" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    outcome : VARCHAR(50)
}

entity "Ball_Recovery" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    offensive : BOOLEAN
}

entity "Block" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    defensive : BOOLEAN
    offensive : BOOLEAN
    save_block : BOOLEAN
    counterpress : BOOLEAN
}

entity "Carry" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    end_location_x : NUMERIC
    end_location_y : NUMERIC
}

entity "Clearance" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    aerial_won : BOOLEAN
    body_part_name : VARCHAR(50)
}

entity "Duel" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    counterpress : BOOLEAN
    duel_type : VARCHAR(25)
    outcome : VARCHAR(50)
}

entity "Foul_Committed" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    counterpress : BOOLEAN
    offensive : BOOLEAN
    foul_type : VARCHAR(25)
    advantage : BOOLEAN
    penalty : BOOLEAN
    card_colour : VARCHAR(25)
}

entity "Foul_Won" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    defensive : BOOLEAN
    advantage : BOOLEAN
    penalty : BOOLEAN
}

entity "Goalkeeper" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    position : VARCHAR(25)
    technique : VARCHAR(50)
    body_part_name : VARCHAR(50)
    goalkeeper_event_type : VARCHAR(50)
    outcome : VARCHAR(50)
}

entity "Half_End" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    early_video_end : BOOLEAN
    match_suspended : BOOLEAN
}

entity "Half_Start" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    late_video_start : BOOLEAN
}

entity "Injury_Stoppage" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    in_chain : BOOLEAN
}

entity "Interception" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    outcome : VARCHAR(25)
}

entity "Miscontrol" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    aerial_won : BOOLEAN
}

entity "Player_Off" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    permanent : BOOLEAN
}

entity "Pressure" {
    * event_id : uuid
    * match_id : INT match_id : INT
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    counterpress : BOOLEAN
}

entity "Substitution" {
    * event_id : uuid
    * match_id : INT 
    event_index : INT
    game_period : INT
    start_time : TIME
    min : INT
    sec : INT
    possession : INT
    possession_team_name : VARCHAR(125)
    play_pattern_name : VARCHAR(50)
    team_name : VARCHAR(125)
    player_name : VARCHAR(125)
    player_position : VARCHAR(50)
    location_x : NUMERIC
    location_y : NUMERIC
    under_pressure : BOOLEAN
    out_of_bounds : BOOLEAN
    duration : NUMERIC
    replacement : VARCHAR(225)
    outcome : VARCHAR(125)
}

Competitions ||--Matches : contains
Matches ||--o Lineups : contains
Matches ||--Pass : contains
Matches ||--Shot : contains
Matches ||-- Dribble : contains
Matches ||-- Dribbled_Past : contains
Matches ||--Bad_Behaviour : contains
Matches ||--Ball_Receipt : contains
Matches ||--Ball_Recovery : contains
Matches ||--Block : contains
Matches ||--Carry : contains
Matches ||--Clearance : contains
Matches ||-- Duel : contains
Matches ||--Foul_Committed : contains
Matches ||--Foul_Won : contains
Matches ||--Goalkeeper : contains
Matches ||--Half_End : contains
Matches ||--Half_Start : contains
Matches ||--Injury_Stoppage : contains
Matches ||--Interception : contains
Matches ||--Miscontrol : contains
Matches ||--Player_Off : contains
Matches ||--Pressure : contains
Matches ||--Substitution : contains

@enduml