CREATE TABLE Competitions (
    competition_id INT,
    season_id INT,
    country_name VARCHAR(255),
    competition_name VARCHAR(255),
    competition_gender VARCHAR(50),
    competition_youth BOOLEAN,
    competition_international BOOLEAN,
    season_name VARCHAR(255),
    PRIMARY KEY (competition_id, season_id)
);

CREATE TABLE Matches (
    match_id INT PRIMARY KEY,
    match_date DATE,
    kick_off TIME,
    country VARCHAR(25),
    competition VARCHAR(50),
    competition_id INT,
    season_id INT,
    home_team VARCHAR(50),
    home_team_gender VARCHAR(25),
    home_team_manager_id INT,
    home_team_manager_name VARCHAR(100),
    home_team_group VARCHAR(25),
    home_team_country VARCHAR(50),
    away_team VARCHAR(50),
    away_team_gender VARCHAR(25),
    away_team_manager_id INT,
    away_team_manager_name VARCHAR(100),
    away_team_group VARCHAR(25),
    away_team_country VARCHAR(50),
    home_score INT,
    away_score INT,
    match_status VARCHAR(25),
    match_week INT,
    competition_stage VARCHAR(25),
    stadium VARCHAR(50),
    stadium_country VARCHAR(25),
    referee_name VARCHAR(125),
    referee_country VARCHAR(50),
    FOREIGN KEY (competition_id, season_id) REFERENCES Competitions(competition_id, season_id)
);

CREATE TABLE Lineups (
    match_id INT PRIMARY KEY,
    lineup_details JSONB,
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Pass (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- pass specific
    recipient_name VARCHAR(125),
    pass_length NUMERIC,
    pass_angle NUMERIC,
    pass_height VARCHAR(50),
    end_location_x NUMERIC,
    end_location_y NUMERIC,
    deflected BOOLEAN,
    is_backheel BOOLEAN,
    is_cross BOOLEAN,
    is_cutback BOOLEAN,
    is_switch BOOLEAN,
    shot_assist BOOLEAN,
    goal_assist BOOLEAN,
    pass_body_part VARCHAR(50),
    pass_type VARCHAR(25),
    outcome_name VARCHAR(50),
    technique VARCHAR(50),
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Shot (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- shots specific
    end_location_x NUMERIC,
    end_location_y NUMERIC,
    end_location_z NUMERIC,
    aerial_won BOOLEAN,
    follows_dribble BOOLEAN,
    first_time BOOLEAN,
    open_goal BOOLEAN,
    statsbomb_xg NUMERIC,
    deflected BOOLEAN,
    technique_name VARCHAR(50),
    body_part_name VARCHAR(50),
    type_name VARCHAR(50),
    outcome_name VARCHAR(50),
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Dribble (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- dribble specific
    overrun BOOLEAN,
    nutmeg BOOLEAN,
    no_touch BOOLEAN,
    outcome VARCHAR(50),
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Dribbled_Past (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- dribble specific
    counterpress BOOLEAN,
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

-- template
-- CREATE TABLE * (
--     event_id uuid PRIMARY KEY,
--     match_id INT,
--     event_index INT,
--     game_period INT,
--     start_time TIME,
--     min INT,
--     sec INT,
--     possession INT,
--     possession_team_name VARCHAR(125),
--     play_pattern_name VARCHAR(50),
--     team_name VARCHAR(125),
--     player_name VARCHAR(125),
--     player_position VARCHAR(50),
--     location_x NUMERIC,
--     location_y NUMERIC,
--     under_pressure BOOLEAN,
--     out_of_bounds BOOLEAN,
--     duration NUMERIC,
--     -- * specific
    
--     FOREIGN KEY (match_id) REFERENCES Matches(match_id)
-- );

CREATE TABLE Bad_Behaviour (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    card_colour VARCHAR(25),
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Ball_Receipt (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    outcome VARCHAR(50),
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Ball_Recovery (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    offensive BOOLEAN,
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Block (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    defensive BOOLEAN,
    offensive BOOLEAN,
    save_block BOOLEAN,
    counterpress BOOLEAN,
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

-- template
CREATE TABLE Carry (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    end_location_x NUMERIC,
    end_location_y NUMERIC,
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Clearance (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    aerial_won BOOLEAN,
    body_part_name VARCHAR(50),
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Duel (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    counterpress BOOLEAN,
    duel_type VARCHAR(25),
    outcome VARCHAR(50),
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Foul_Committed (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    counterpress BOOLEAN,
    offensive BOOLEAN,
    foul_type VARCHAR(25),
    advantage BOOLEAN,
    penalty BOOLEAN,
    card_colour VARCHAR(25),
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Foul_Won (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    defensive BOOLEAN,
    advantage BOOLEAN,
    penalty BOOLEAN,
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Goalkeeper (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    position VARCHAR(25),
    technique VARCHAR(50),
    body_part_name VARCHAR(50),
    goalkeeper_event_type VARCHAR(50),
    outcome VARCHAR(50),
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Half_End (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    early_video_end BOOLEAN,
    match_suspended BOOLEAN,
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Half_Start (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    late_video_start BOOLEAN,
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Injury_Stoppage (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    in_chain BOOLEAN,
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Interception (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    outcome VARCHAR(25),
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Miscontrol (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    aerial_won BOOLEAN,
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Player_Off (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    permanent BOOLEAN,
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Pressure (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    counterpress BOOLEAN,
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

CREATE TABLE Substitution (
    event_id uuid PRIMARY KEY,
    match_id INT,
    event_index INT,
    game_period INT,
    start_time TIME,
    min INT,
    sec INT,
    possession INT,
    possession_team_name VARCHAR(125),
    play_pattern_name VARCHAR(50),
    team_name VARCHAR(125),
    player_name VARCHAR(125),
    player_position VARCHAR(50),
    location_x NUMERIC,
    location_y NUMERIC,
    under_pressure BOOLEAN,
    out_of_bounds BOOLEAN,
    duration NUMERIC,
    -- * specific
    replacement VARCHAR(225),
    outcome VARCHAR(125),
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);